global: 
  enabled: false
  name: consul
server:
  enabled: true
  replicas: 1
  exposeGossipAndRPCPorts: true
  ports:
    serflan: 
      port: 9301
  storage: 1Gi
client:
  exposeGossipPorts: true
ui:
  enabled: true
  service:
    type: LoadBalancer
    annotations: |
      'lbipam.cilium.io/ips': 10.5.0.137
  # ingress:
  #   enabled: true
  #   hosts:
  #     - host: consul-hawkv6.stud.network.garden
dns: 
  enabled: false
connectInject:
  enabled: false
