---
cells:
  "link_id:clab-hawkv6-HOST-C:eth1:clab-hawkv6-SITE-C:Gi0-0-0-1":
    dataRef: "SITE-C-G0-0-0-1-in"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-SITE-C:Gi0-0-0-1:clab-hawkv6-HOST-C:eth1":
    dataRef: "SITE-C-G0-0-0-1-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-HOST-B:eth1:clab-hawkv6-SITE-B:Gi0-0-0-1":
    dataRef: "SITE-B-G0-0-0-1-in"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-SITE-B:Gi0-0-0-1:clab-hawkv6-HOST-B:eth1":
    dataRef: "SITE-B-G0-0-0-1-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-SITE-C:Gi0-0-0-0:clab-hawkv6-XR-8:Gi0-0-0-3":
    dataRef: "SITE-C-G0-0-0-0-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-XR-8:Gi0-0-0-3:clab-hawkv6-SITE-C:Gi0-0-0-0":
    dataRef: "XR-8-G0-0-0-3-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-SITE-B:Gi0-0-0-0:clab-hawkv6-XR-8:Gi0-0-0-2":
    dataRef: "SITE-B-G0-0-0-0-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-XR-8:Gi0-0-0-2:clab-hawkv6-SITE-B:Gi0-0-0-0":
    dataRef: "XR-8-G0-0-0-2-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-SITE-C:Gi0-0-0-2:clab-hawkv6-XR-7:Gi0-0-0-4":
    dataRef: "SITE-C-G0-0-0-2-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-XR-7:Gi0-0-0-4:clab-hawkv6-SITE-C:Gi0-0-0-2":
    dataRef: "XR-7-G0-0-0-4-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-XR-8:Gi0-0-0-1:clab-hawkv6-XR-7:Gi0-0-0-3":
    dataRef: "XR-8-G0-0-0-1-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-XR-7:Gi0-0-0-3:clab-hawkv6-XR-8:Gi0-0-0-1":
    dataRef: "XR-7-G0-0-0-3-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-XR-8:Gi0-0-0-0:clab-hawkv6-XR-6:Gi0-0-0-3":
    dataRef: "XR-8-G0-0-0-0-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-XR-6:Gi0-0-0-3:clab-hawkv6-XR-8:Gi0-0-0-0":
    dataRef: "XR-6-G0-0-0-3-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-SITE-B:Gi0-0-0-2:clab-hawkv6-XR-6:Gi0-0-0-4":
    dataRef: "SITE-B-G0-0-0-2-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-XR-6:Gi0-0-0-4:clab-hawkv6-SITE-B:Gi0-0-0-2":
    dataRef: "XR-6-G0-0-0-4-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-XR-6:Gi0-0-0-2:clab-hawkv6-XR-7:Gi0-0-0-2":
    dataRef: "XR-6-G0-0-0-2-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-XR-7:Gi0-0-0-2:clab-hawkv6-XR-6:Gi0-0-0-2":
    dataRef: "XR-7-G0-0-0-2-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-XR-7:Gi0-0-0-1:clab-hawkv6-XR-5:Gi0-0-0-2":
    dataRef: "XR-7-G0-0-0-1-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-XR-5:Gi0-0-0-2:clab-hawkv6-XR-7:Gi0-0-0-1":
    dataRef: "XR-5-G0-0-0-2-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-XR-6:Gi0-0-0-1:clab-hawkv6-XR-5:Gi0-0-0-1":
    dataRef: "XR-6-G0-0-0-1-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-XR-5:Gi0-0-0-1:clab-hawkv6-XR-6:Gi0-0-0-1":
    dataRef: "XR-5-G0-0-0-1-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-XR-5:Gi0-0-0-0:clab-hawkv6-XR-4:Gi0-0-0-2":
    dataRef: "XR-5-G0-0-0-0-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-XR-4:Gi0-0-0-2:clab-hawkv6-XR-5:Gi0-0-0-0":
    dataRef: "XR-4-G0-0-0-2-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-XR-7:Gi0-0-0-0:clab-hawkv6-XR-3:Gi0-0-0-3":
    dataRef: "XR-7-G0-0-0-0-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-XR-3:Gi0-0-0-3:clab-hawkv6-XR-7:Gi0-0-0-0":
    dataRef: "XR-3-G0-0-0-3-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-XR-4:Gi0-0-0-1:clab-hawkv6-XR-3:Gi0-0-0-2":
    dataRef: "XR-4-G0-0-0-1-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-XR-3:Gi0-0-0-2:clab-hawkv6-XR-4:Gi0-0-0-1":
    dataRef: "XR-3-G0-0-0-2-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-XR-4:Gi0-0-0-0:clab-hawkv6-XR-2:Gi0-0-0-2":
    dataRef: "XR-4-G0-0-0-0-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-XR-2:Gi0-0-0-2:clab-hawkv6-XR-4:Gi0-0-0-0":
    dataRef: "XR-2-G0-0-0-2-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-XR-6:Gi0-0-0-0:clab-hawkv6-XR-2:Gi0-0-0-1":
    dataRef: "XR-6-G0-0-0-0-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-XR-2:Gi0-0-0-1:clab-hawkv6-XR-6:Gi0-0-0-0":
    dataRef: "XR-2-G0-0-0-1-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-XR-3:Gi0-0-0-1:clab-hawkv6-XR-2:Gi0-0-0-3":
    dataRef: "XR-3-G0-0-0-1-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-XR-2:Gi0-0-0-3:clab-hawkv6-XR-3:Gi0-0-0-1":
    dataRef: "XR-2-G0-0-0-3-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-XR-3:Gi0-0-0-0:clab-hawkv6-XR-1:Gi0-0-0-2":
    dataRef: "XR-3-G0-0-0-0-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-XR-1:Gi0-0-0-2:clab-hawkv6-XR-3:Gi0-0-0-0":
    dataRef: "XR-1-G0-0-0-2-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-XR-2:Gi0-0-0-0:clab-hawkv6-XR-1:Gi0-0-0-1":
    dataRef: "XR-2-G0-0-0-0-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-XR-1:Gi0-0-0-1:clab-hawkv6-XR-2:Gi0-0-0-0":
    dataRef: "XR-1-G0-0-0-1-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-XR-1:Gi0-0-0-0:clab-hawkv6-SITE-A:Gi0-0-0-0":
    dataRef: "XR-1-G0-0-0-0-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-SITE-A:Gi0-0-0-0:clab-hawkv6-XR-1:Gi0-0-0-0":
    dataRef: "SITE-A-G0-0-0-1-out"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-HOST-A:eth1:clab-hawkv6-SITE-A:Gi0-0-0-1":
    dataRef: "SITE-A-G0-0-0-0-in"
    label:
      units: "binBps"
      decimalPoints: 0

  "link_id:clab-hawkv6-SITE-A:Gi0-0-0-1:clab-hawkv6-HOST-A:eth1":
    dataRef: "SITE-A-G0-0-0-0-out"
    label:
      units: "binBps"
      decimalPoints: 0